### ISSUE TITLE
mp4 to obj file issue

### ISSUE THREAD

**Issue by AsmaeOUHSSAIN** [priorMDM/priorMDM#10]
Hi Sir,

First of all, thank you for the excellent job that you did. 

I am contacting you because I have a question about priorMDM usage. I'm encountering an issue during the visualization process, specifically when using the command line "python -m visualize.render_mesh --input_path /path/to/mp4/stick/figure/file" to convert an mp4 file to an obj file. I then tried to visualise the obj files using Blender but I noticed that there was only one mesh present instead of two. In the original mp4 file, there are two persons with joint representation, and I have been unable to identify the precise cause of the issue. For this, I used render.py, which is located in the visualization folder.

Thank you in advance for your response.

Sincerely,
Asmae

**Comment by priorMDM** [comment]
Hello @AsmaeOUHSSAIN , 
This seems like a bug and we will make an effort to fix it soon. In the meantime please try and rerun the `render_mesh` script, but in the following line:
https://github.com/priorMDM/priorMDM/blob/c0129a76fc6c3d68bbeab9c36595ef23e1e84232/visualize/vis_utils.py#L28
change `motion` to `other_motion` - that should generate the obj for the other person in the scene. You can then should be able to combine them in blender. Please let me know if this temp fix works.
