### ISSUE TITLE
File `dataset/babel/babel-smplh-30fps-male/../babel-teach/val.json` is missing

### ISSUE THREAD

**Issue by felixdivo** [priorMDM/priorMDM#15]
Is it possible that some dependency is missing from the README?

When I run `python -m sample.double_take --model_path ./save/Babel_TrasnEmb_GeoLos/model000850000.pt --dataset babel --handshake_size 20 --blend_len 10`, I get the fowllowing output:

```
generating samples
Loading dataset...
Traceback (most recent call last):
  [some debugger stuff]
  File "/workspaces/text2animation/priorMDM/sample/double_take.py", line 281, in <module>
    main()
  File "/workspaces/text2animation/priorMDM/sample/double_take.py", line 95, in main
    data = load_dataset(args, n_frames)
  File "/workspaces/text2animation/priorMDM/sample/double_take.py", line 270, in load_dataset
    data = get_dataset_loader(name=args.dataset,
  File "/workspaces/text2animation/priorMDM/data_loaders/get_data.py", line 75, in get_dataset_loader
    dataset = get_dataset(name, num_frames, split, load_mode, batch_size, opt, short_db, cropping_sampler, size)
  File "/workspaces/text2animation/priorMDM/data_loaders/get_data.py", line 63, in get_dataset
    dataset = DATA(split=split,
  File "/workspaces/text2animation/priorMDM/data_loaders/amass/babel.py", line 396, in __init__
    self.babel_annots = read_json(Path(datapath) / f'../babel-teach/{split}.json')
  File "/workspaces/text2animation/priorMDM/data_loaders/amass/file_io.py", line 21, in read_json
    with open(p, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/babel/babel-smplh-30fps-male/../babel-teach/val.json'
```

Note, that `dataset/babel/babel-smplh-30fps-male` exists as explained in the README.

**Comment by felixdivo** [comment]
Well, so it worked when I added the data from [here](https://teach.is.tue.mpg.de/download.php). I guess this should be added to the README?

**Comment by priorMDM** [comment]
Thanks and sorry for the slow respond.
It is actually appears in the readme,
under:
Get PriorMDM dependencies 
Download the processed version [here](https://drive.google.com/file/d/18a4eRh8mbIFb55FMHlnmI8B8tSTkbp4t/view?usp=share_link), and place it at ./dataset/babel

didn't it work for you?

**Comment by felixdivo** [comment]
But then I only get `babel-smplh-30fps-male.zip`, and when I extract it I get:

```shell
root $ unzip babel-smplh-30fps-male.zip
Archive:  babel-smplh-30fps-male.zip
   creating: babel-smplh-30fps-male/
  inflating: babel-smplh-30fps-male/.DS_Store  
  inflating: __MACOSX/babel-smplh-30fps-male/._.DS_Store  
  inflating: babel-smplh-30fps-male/val_tiny.pth.tar  
  inflating: babel-smplh-30fps-male/train_tiny.pth.tar  
  inflating: babel-smplh-30fps-male/train.pth.tar  
  inflating: babel-smplh-30fps-male/val.pth.tar  
```

So the `babel-teach` folder is missing.

**Comment by RushToNeverLand** [comment]
+1，the babel-teach folder is missing.

**Comment by yonishafir** [comment]
Thanks you for the notice and sorry for the delay,
I added the additional needed download to the readme file. 
[babel-teach](https://drive.google.com/file/d/1PBlbxawaeFTxtKkKDsoJwQGuDTdp52DD/view?usp=sharing), should be placed as well under dataset/babel

**Comment by felixdivo** [comment]
Thank you! I guess this is solved now. If not, I'll open a new issue.
