### ISSUE TITLE
How to input the skeleton of the first frame

### ISSUE THREAD

**Issue by LiuShiyu95** [priorMDM/priorMDM#21]
Thank you for your great job!

I tried to follow the preprocessing of the HumanML3D dataset for the first frame of the mesh data, but since the output of the motion process is the number of frames -1 of the input, I would like to ask you how to insert the first frame

**Comment by GuyTevet** [comment]
Can you let me know which script were you running, and the error print you got?

**Comment by LiuShiyu95** [comment]
Thank you for your help.

When I process the motion_representation.ipynb file in HumanML3D, the length of the input before executing the def process_file function is sequence, and the length of the output is sequence-1. Currently, I only have one pose, and I don't know how to execute this method correctly to complete data preprocessing.

**Comment by GuyTevet** [comment]
To the best of my knowledge, this process doesn't support single-frame poses, since it involves velocity calculation. Please contact the humanml team in https://github.com/EricGuo5513/HumanML3D

**Comment by LiuShiyu95** [comment]
Thank you for your reply. I have caused you a lot of trouble recently. Thank you very much for your help during this period.

**Comment by GuyTevet** [comment]
Haha don't worry you are welcome:)
