### ISSUE TITLE
Error occured when reproducing DoubleTake evaluation

### ISSUE THREAD

**Issue by Xiyan-Xu** [priorMDM/priorMDM#22]
Here is the error I encounted when I tried to evaluate pretrained DoubleTake model, following the instruction of README.
![error](https://github.com/priorMDM/priorMDM/assets/58477124/312e10b4-6602-49de-bd20-b382b01acd41)
It seems that eval_multi.py cannot rcongnize some arguments, maybe I should use eval_humanml_double_take.py to evaluate model instead

**Comment by yonishafir** [comment]
Thank you for your comment, 
There was indeed a typo within the bash command. 

for evaluating doubleTake please use the fixed bash commands that can be found in the updated readme file at the Evaluation part
