### ISSUE TITLE
Question regarding Cropping motions in dataloader

### ISSUE THREAD

**Issue by siddharthKatageri** [priorMDM/priorMDM#23]
Had some questions from the dataloader part.

1. Why do we want to Crop the motions into times of 4 in the dataloader? As in [here](https://github.com/priorMDM/priorMDM/blob/260dcc108a52623f78c0bd6bb441fb02aa1715b7/data_loaders/humanml/data/dataset.py#L370).
If we have a motion of length that is not divisible by 4 and less than maximum motion length, we are going to pad it with zero's anyways, as in [here](https://github.com/priorMDM/priorMDM/blob/260dcc108a52623f78c0bd6bb441fb02aa1715b7/data_loaders/humanml/data/dataset.py#L386).
2. While testing as I have a constraint in my task that I cannot crop my input motion, would ignoring this cropping my input motion result in bad behavior from MDM?
3. Also, instead of cropping, would padding the input with duplicate start/end frames to make it divisible by 4 be fine?

Thanks!

**Comment by GuyTevet** [comment]
1. That's not necessary for MDM/ProrMDM just a legacy from https://github.com/EricGuo5513/text-to-motion
2. No
3. Just remove the cropping feature all together, it's redundant in our context

Hope it helps:)

**Comment by siddharthKatageri** [comment]
Thanks!
