### ISSUE TITLE
Confusion about MDM in-painting in comparison videos

### ISSUE THREAD

**Issue by boyuaner** [priorMDM/priorMDM#24]
<img width="890" alt="image" src="https://github.com/priorMDM/priorMDM/assets/32932640/166634ec-4434-4ae2-bdd5-8a569e23cad4">
Why is there a gap between the left hand and the trajectory here? I have seen that MDM's in-painting method also masks out the noise that should be added during inference, So according to my understanding, this kind of situation should not occur.

![image](https://github.com/priorMDM/priorMDM/assets/32932640/8f36853f-8f57-4be4-b6bb-0c88dc7a21d4)

#https://github.com/GuyTevet/motion-diffusion-model/issues/119

**Comment by GuyTevet** [comment]
Yup @boyuaner good observation! The gap is caused by the SMPLify post-process that converts joint locations to SMPL angles. Considering the original joint locations only (as in the stick figure visualizations) there is no gap (for either MDM or PriorMDM)

**Comment by boyuaner** [comment]
So is it because PriorMDM used different post-processing methods so we get the better visualization result(no gap between hand and trajectory)?

**Comment by boyuaner** [comment]
Thank you for your patience:)
