### ISSUE TITLE
name 'data' is not defined 

### ISSUE THREAD

**Issue by zhenglinpan** [priorMDM/priorMDM#25]
Hi:

Thanks for your excellent work! 

I noticed there might be a minor bug in evaluation.

### Re-implementation: 
run `python -m eval.eval_humanml_double_take --model_path ./save/my_humanml_trans_enc_512/model000200000.pt --num_unfoldings 2 --handshake_size 20 --transition_margins 40  --eval_on motion --blend_len 10`
or 
`python -m eval.eval_humanml_double_take --model_path ./save/my_humanml_trans_enc_512/model000200000.pt --num_unfoldings 2 --handshake_size 20 --transition_margins 40  --eval_on transition --blend_len 10`
as in tutorial, it raises an error 

### Error
```bash
(PriorMDM) zhenglin@LAPTOP-LEGION:~/3DMotion/priorMDM$ python -m eval.eval_humanml_double_take --model_path ./save/my_humanml_trans_enc_512/model000200000.pt --num_unfoldings 2 --handshake_size 20 --transition_margins 40  --eval_on transition --blend_len 10
Warning: was not able to load [use_tta], using default value [False] instead.
Warning: was not able to load [concat_trans_emb], using default value [False] instead.
Warning: was not able to load [trans_emb], using default value [False] instead.
Will save to log file [./save/my_humanml_trans_enc_512/eval_humanml_FinalFINALLLLLL_my_humanml_trans_enc_512_000200000_gscale2.5_transition_False_wo_mm_handshake_20_doubleTake_blend_10_skipSteps_100_transiton_margin_4010_rep_on_transition_humanml.log]
Eval mode [wo_mm]
Logging to /tmp/openai-2023-10-10-17-56-38-143235
creating data loader...
Reading ././dataset/humanml_opt.txt
Loading dataset t2m ...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4384/4384 [00:01<00:00, 3768.68it/s]
Pointer Pointing at 0
Reading ././dataset/humanml_opt.txt
Loading dataset t2m ...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4384/4384 [00:01<00:00, 4117.63it/s]
Pointer Pointing at 0
Creating model and diffusion...
Traceback (most recent call last):
  File "/home/zhenglin/anaconda3/envs/PriorMDM/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zhenglin/anaconda3/envs/PriorMDM/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zhenglin/3DMotion/priorMDM/eval/eval_humanml_double_take.py", line 303, in <module>
    model, diffusion = load_model(args, data, dist_util.dev(), ModelClass=doubleTake_MDM)
NameError: name 'data' is not defined
```

The code works fine for the command `python -m eval.eval_multi --model_path ./save/pw3d_prefix/model000240000.pt` in evaluating ComMDM, I presume the issue is only related to DoubleTake.

I've checked the `eval_humanml_double_take.py` file and found that in line 303, there is a `data` out of nowhere, not even from the package the file imports. 

I assume this is a bug?

**Comment by BarqueroGerman** [comment]
Try replacing "data" with "gen_loader". It worked for me.

**Comment by zhenglinpan** [comment]
> Try replacing "data" with "gen_loader". It worked for me.

Thanks bro, it worked for me too, but I'm not sure if that's the correct way to solve this issue

**Comment by GuyTevet** [comment]
Thanks, I will take a look

**Comment by GuyTevet** [comment]
Thanks @BarqueroGerman indeed that was the fix:)
