### ISSUE TITLE
T2M evaluator for BABEL: file missing

### ISSUE THREAD

**Issue by BarqueroGerman** [priorMDM/priorMDM#26]
Hey!

Congratulations on this very nice piece of work. I am trying to reproduce your results on the BABEL dataset but I think that a file might be missing. When running the eval_babel script:

`FileNotFoundError: [Errno 2] No such file or directory: './dataset/babel/text_mot_match_babel_random_motion_bs64/model/finest.tar'
`

This file is not inside the BABEL folders you uploaded to Google Drive.

Thanks in advance!

**Comment by GuyTevet** [comment]
Thank you @BarqueroGerman for raising this issue. I added the missing file and updated the README link. Please confirm to me that the issue was resolved on your end.

**Comment by teshima058** [comment]
I tried eval_finetuned_motion_control.py on the humanml dataset and there was no checkpoint file.
Would you also add './daaset/t2m/text_mot_match/model/finest.tar' ?

**Comment by teshima058** [comment]
Sorry, I found it in the t2m project.
https://github.com/EricGuo5513/text-to-motion?tab=readme-ov-file#:~:text=Download%20models%20for%20HumanML3D%20from%20%5Bhere%5D.
