### ISSUE TITLE
Question about Visualizasion of GT_motion in 3DPW Dataset

### ISSUE THREAD

**Issue by 1311894932** [priorMDM/priorMDM#28]
After i run the command：
python -m sample.two_person_text2motion --model_path ./save/my_humanml_trans_enc_512/model000200000.pt --sample_gt

it visualize 10 motion in dataset 3DPW, but some of them are not right...especially dancing because the two person back to back instead of face to face, but motion "exercise" is natural. 

i dont know why and i'm confused for a long time...maybe i should re-download and re-run the project??

any response will be appreciated!!!

**Comment by 1311894932** [comment]
In my opinion, i think probably the canon data is a little...weird? i mean if the visualizasion function was wrong, motion "exercise" wont be natural.

**Comment by 1311894932** [comment]
ok i've re-downloaded and re-run the project, there is indeed a problem

**Comment by 1311894932** [comment]
Now I have another idea !!!
I do think the rotation function dont make sense to the SAMPLE1:

_rot0 = geometry.rotation_6d_to_matrix(canon0[:, :6])
_rot1 = geometry.rotation_6d_to_matrix(canon1[:, :6])
diff_rot = torch.matmul(_rot0, _rot1.permute(0, 2, 1)).float().cpu()
...
sample1 = torch.matmul(diff_rot.view(-1, 1, 1, 1, 3, 3), sample1.unsqueeze(-1)).squeeze(-1)
sample1 = sample1.view(-1, *sample1.shape[2:]).permute(0, 2, 3, 1).cpu().numpy()
sample1 += diff_trans.view(-1, 1, 3, 1).cpu().numpy()

**Comment by GuyTevet** [comment]
The canon data is indeed not perfect.

**Comment by 1311894932** [comment]
> The canon data is indeed not perfect.

thanks so much !! Thank you for your reply
