### ISSUE TITLE
Soft Blending Bug in inpainting mask

### ISSUE THREAD

**Issue by RalphHan** [priorMDM/priorMDM#29]
https://github.com/priorMDM/priorMDM/blob/8bc565b3120c08182f067e161e83403b0efe7cc9/utils/sampling_utils.py#L94
@priorMDM @yonishafir I saw you commented Line 94，which makes it different from the paper. Is there a reason?
<img width="656" alt="image" src="https://github.com/priorMDM/priorMDM/assets/37136590/782cb7ac-1f56-413e-ad6e-dc8a21fe43ba">

**Comment by yonishafir** [comment]
No specific reason, I'll update a new version of this code later.
basically, as you can notice in lines 96:99, the default value for the M_soft is 0.0 (as the soft blending values goes from 0.85 to 0.0).
A better practice (which supposed to be updated later), is using M_soft and M_hard as input arguments.
