### ISSUE TITLE
Evaluation on DoubleTake

### ISSUE THREAD

**Issue by exitudio** [priorMDM/priorMDM#30]
Thank you for your amazing work. 
I have a question about the evaluation on HumanML3D of DoubleTake.
Can you explain how you can evaluate the "Motion" and "Transition" on HumanML3D? (Since their is no ground truth transition in this dataset)

**Comment by yonishafir** [comment]
Thanks for your question. 
Regarding the evaluation of HumanML3D (same goes for BABEL) of DoubleTake, I'd like to split the answer to two.

First, basically its the same idea as evaluating motion as been explained in this paper and other like MDM and T2M (please let me know if any explanation needed regarding the metrics and the classifier training), we evaluate for each long motion by splitting each motion to two parts: Motion and Transition. 

for the **Motion Evaluation:** for each long motion we take all the motion parts (e.g., the part of the long sequence that is not within the transition, and we evaluate for each motion using its own text. 

each sequence is defined as follows:
=================== ====== ===============. ====== =================
||      Motion_0                 ||     T_0     ||           Motion_1.    ||.    T_1     ||            Motion_2.       ||
=================== =====.  =============== ====== =================
So we take just the motion parts and evaluate each separately measuring our matrices as been measured for each t2m in other papers (as we also have GT for those we can measure R-precision, FID, Diversity and  MultiModal-Dist ).

for the Transition part, as we don't have any transition ground truth, all we ask for is a natural from distribution motion.
thus we trained our classifier for motion sequences within the lengths we ask our transition to be. 
then we measure FID and diversity just to be from the distribution of other motions (by taking only the transition parts as the generated motion).  
please check: https://github.com/priorMDM/priorMDM/blob/main/eval/eval_humanml_double_take.py#L292 
for any code reference. 

let me know if something is still does not work out for you
