### ISSUE TITLE
Question about 3PDW dataset.

### ISSUE THREAD

**Issue by 2022yingjie** [priorMDM/priorMDM#31]
When I checked the shape of data loaded from 3PDW dataset, it showed as [64,263,1,60], I want to know what dose the dimension '263' represent?

**Comment by GuyTevet** [comment]
It's a processed pose vector, aligned with the HumanML3D representation as presented in [HumanML3D paper](https://openaccess.thecvf.com/content/CVPR2022/papers/Guo_Generating_Diverse_and_Natural_3D_Human_Motions_From_Text_CVPR_2022_paper.pdf).

![image](https://github.com/priorMDM/priorMDM/assets/24757373/96230986-66d9-4ca2-8209-813b0fcde0bc)
