### ISSUE TITLE
About Babel evaluation problem

### ISSUE THREAD

**Issue by SupstarZh** [priorMDM/priorMDM#36]
Thanks for the wonderful work!
I have a problem with evaluating the **Babel dataset** using the **Double Take** method.
Does the bash commands given in the readme right?
`python -m eval.eval_multi --model_path ./save/Babel_TrasnEmb_GeoLoss/model001250000.pt --num_unfoldings 2 --cropping_sampler --handshake_size 30 --transition_margins 40  --eval_on motion --blend_len 10
`
I guess eval_multi.py file is used to evaluate the ComMDM?
and maybe the right command is` python -m eval.eval_babel`? or` eval.eval_humanml_double_take`? and need a extra param` --dataset babel` ?
Can you give me a right bash command to evaluate the babel? Thanks!

**Comment by yonishafir** [comment]
Hey, you are absolutely right! 
it will take me some time to validate that, but there was a typo in to read me w/o a doubt. 

In the meantime can you please try the following ? 

for motion: 

python -m eval.eval_babel --model_path ./save/Babel_TrasnEmb_GeoLoss/model001250000.pt --num_unfoldings 2 --cropping_sampler --handshake_size 30 --transition_margins 40  --eval_on motion --blend_len 10 —dataset babel

for transitions 
python -m eval.eval_babel --model_path ./save/Babel_TrasnEmb_GeoLoss/model001250000.pt --num_unfoldings 2 --cropping_sampler --handshake_size 30 --transition_margins 40  --eval_on transition --blend_len 10 —dataset babel

**Comment by SupstarZh** [comment]
Thanks!
This solved my problems
