### ISSUE TITLE
About Dataset “Babel”

### ISSUE THREAD

**Issue by bojin-nwafu** [priorMDM/priorMDM#5]
Thank you for publishing such outstanding work！

When I was training 'train_mdm.py' using the Babel dataset, I was informed that **the file 'train.pth.tar' was not present in the dataset and was missing from the published data file.**

**Comment by priorMDM** [comment]
Hi, 
Were you following the readme file?

At section 3. Get PriorMDM dependencies
Please download the processed version of the dataset, unzip it and place it under dataset/babel

If you have done that, please share some more information about what error exactly did you get

**Comment by priorMDM** [comment]
I've noticed that the babel dataset folder was corrupted.
Please download the following (and remove the previous):
https://drive.google.com/file/d/18a4eRh8mbIFb55FMHlnmI8B8tSTkbp4t/view?usp=share_link
