### ISSUE TITLE
Downloaded model files are duplicates

### ISSUE THREAD

**Issue by guanchongz** [priorMDM/priorMDM#6]
![image](https://user-images.githubusercontent.com/31274074/235048723-552fcb46-bab5-48df-834d-f9dd32194633.png)
The md5 codes of these two files are exactly the same, is it wrong to upload?

**Comment by jihg88** [comment]
hello ,Have you run these models, how to deal with the missing model.args files?
It  just asserted 'Arguments json file was not found!' when i run the first model.

**Comment by priorMDM** [comment]
Hey, 
thank you for the notice.
I've updated all the fine-tune pre-trained models links, please check the readme file and download again.

Thanks.

**Comment by priorMDM** [comment]
Done - readme updated with correct links
