### ISSUE TITLE
Solving the environment

### ISSUE THREAD

**Issue by tommyshelby4** [priorMDM/priorMDM#8]
Are you sure the .yml file for setting up the environment works fine? I get an error like this:
![image](https://user-images.githubusercontent.com/36934521/235633650-32aeb962-bacb-419b-bc67-37f31c650d63.png)

**Comment by priorMDM** [comment]
Works for me (Double checked), are you working on a Linux machine?

**Comment by tabsun** [comment]
Check this issue [here](https://github.com/conda/conda/issues/9590)
it solves my similar problem.
