### ISSUE TITLE
Fails to stack videos

### ISSUE THREAD

**Issue by mmdrahmani** [priorMDM/priorMDM#9]
Hi. Thanks for the great work!

I am trying to produce some long sequence of actions, with 10 repetitions. But the mp4 video contains only one repetition. And a warning below is given:
` Cannot find a matching stream for unlabeled input pad 1 on filter Parsed_hstack_0`
Any ideas how to solve this problem? This is the size of `-filter_complex hstack=inputs=10`.

Thanks
Mohammad

**Comment by priorMDM** [comment]
Thanks for reaching out! 
can you please share with the command you're using for this that causes this issue?

**Comment by mmdrahmani** [comment]
Thanks for your reply. 
I am just using the example code provided:
` python -m sample.double_take --model_path ./save/my_humanml_trans_enc_512/model000200000.pt --num_repetition 10 --handshake_size 10 --blend_len 10 --input_text ./assets/stick_attack.txt `

Then after the samples are generated, I get a ffmpeg warning `Cannot find a matching stream for unlabeled input pad 1 on filter Parsed_hstack_0`

Thank you
Mohammad

**Comment by mmdrahmani** [comment]
Thanks for the reply.
I had no problem running this command above. I can run it and get the results. But the problem shows up when using `--num_repetition` larger than one. In such cases there is this warning `Cannot find a matching stream for unlabeled input pad 1 on filter Parsed_hstack_0`, which is related to stacking multiple videos into a single mp4 file. The `results.npy` file actually contains all the repetitions defined by `--num_repetition`. 
My guess is that the ffmpeg is different in my setup, so horizontal stacking fails. I could not find a solution.
Bests
Mohammad

**Comment by priorMDM** [comment]
Hi again, I understand the issue. 
currently, for this current code version, we did not added support for number of reparations larger than 1. 
we have some bug fix and improvements in our pipe, that will be committed soon. 
Currently please use only with repartition=1

**Comment by mmdrahmani** [comment]
I see. Thanks a lot for your support.
Great work!

**Comment by priorMDM** [comment]
Thanks a lot!
Closing this issue, will reopen and respond once we will add the option of having reparation larger than 1
